#!/bin/bash

# QUICK START GUIDE - Vision-Based Autonomous RC Car Control System

echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║  Vision-Based Autonomous RC Car Control System - SETUP     ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# Get the script directory
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPT_DIR"

echo "Project Directory: $SCRIPT_DIR"
echo ""

# Check Python virtual environment
if [ ! -d ".venv" ]; then
    echo "[*] Virtual environment not found. Creating..."
    python3 -m venv .venv
    echo "[✓] Virtual environment created"
else
    echo "[✓] Virtual environment exists"
fi

# Activate virtual environment
echo "[*] Activating virtual environment..."
source .venv/bin/activate
echo "[✓] Virtual environment activated"
echo ""

# Show menu
echo "╔════════════════════════════════════════════════════════════╗"
echo "║                    AVAILABLE COMMANDS                      ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "  1) python run_autonomy.py --simulate"
echo "     → Run in simulation mode (no hardware needed)"
echo "     → Perfect for testing and tuning"
echo ""
echo "  2) python run_autonomy.py --list-devices"
echo "     → List all available BLE devices"
echo "     → Find your car's device index"
echo ""
echo "  3) python run_autonomy.py --device-index N --duration 60"
echo "     → Connect to car at device index N"
echo "     → Run for 60 seconds (0 = unlimited)"
echo ""
echo "  4) python test_complete_demo.py"
echo "     → Run complete system demonstration"
echo "     → Validates all components"
echo ""
echo "  5) python test_ble_python.py"
echo "     → Test BLE connection to car"
echo "     → Verify car is powered and discoverable"
echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║                  GETTING STARTED                           ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "Step 1: Test the system (no hardware needed)"
echo "  $ python run_autonomy.py --simulate"
echo ""
echo "Step 2: List available BLE devices"
echo "  $ python run_autonomy.py --list-devices"
echo ""
echo "Step 3: Power on your RC car (make sure it's discoverable)"
echo "  → Look for your car in the device list"
echo "  → Note its index number"
echo ""
echo "Step 4: Run with your car"
echo "  $ python run_autonomy.py --device-index <N> --duration 30"
echo "  → Replace <N> with your car's index"
echo ""
echo "Step 5: Follow on-screen instructions"
echo "  → Select the car region (ROI) in the camera window"
echo "  → Click and drag to draw box around car"
echo "  → Press SPACE to confirm"
echo "  → System starts autonomous tracking"
echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║                 CONFIGURATION TIPS                         ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "Edit config/default.json to tune:"
echo ""
echo "  • Camera resolution (640x480 recommended for Pi4)"
echo "  • Tracking algorithm (KCF is most stable)"
echo "  • Boundary detection threshold (50-100 typical)"
echo "  • Ray angles and distances"
echo "  • Default speed and steering sensitivity"
echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║                  RUNTIME CONTROLS                          ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "While running:"
echo ""
echo "  • Press 'q' in the display window → graceful quit"
echo "  • Press Ctrl+C in terminal → stop (sends STOP command)"
echo "  • Duration limit reached → automatic shutdown"
echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║                 PROJECT STRUCTURE                          ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "  rc_autonomy/          - Core Python modules"
echo "  ├── ble.py           - BLE communication"
echo "  ├── camera.py        - Camera capture"
echo "  ├── tracking.py      - Object tracking"
echo "  ├── boundary.py      - Boundary detection & guidance"
echo "  ├── commands.py      - Command formatting"
echo "  ├── config.py        - Configuration loading"
echo "  ├── orchestrator.py  - Multi-threaded coordinator"
echo "  └── ui.py            - Visualization"
echo ""
echo "  config/               - Configuration files"
echo "  └── default.json      - Tunable parameters"
echo ""
echo "  docs/                 - Documentation"
echo "  ├── PRD.md           - Product requirements"
echo "  └── README_BUILD.md  - Build instructions"
echo ""
echo "  run_autonomy.py      - Main entry point"
echo "  test_complete_demo.py - Full system test"
echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║              TROUBLESHOOTING                               ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "Q: Car not found in device list?"
echo "A: 1. Make sure car is powered ON"
echo "   2. Enable Bluetooth on your Mac/Pi"
echo "   3. Try manual pairing first"
echo "   4. Run: python run_autonomy.py --list-devices"
echo ""
echo "Q: Camera not opening?"
echo "A: 1. Check camera is plugged in"
echo "   2. Try: python diagnose_camera.py"
echo "   3. Edit config/default.json to adjust source index"
echo ""
echo "Q: Tracking lost immediately?"
echo "A: 1. Make sure car is clearly visible in ROI"
echo "   2. Try different lighting conditions"
echo "   3. Switch tracker in config (try CSRT or GOTURN)"
echo ""
echo "Q: Car not responding to commands?"
echo "A: 1. Test with: python test_car_control.py"
echo "   2. Check BLE connection is stable"
echo "   3. Verify characteristic UUID in config"
echo ""
echo ""
echo "📖 For more details, see PROJECT_COMPLETION.md"
echo ""
